bind_ws_addr = "127.0.0.1:8080"

[source]
dedup_queue_size = 50000
rpc_ws_url = ""

[[source.grpc_sources]]
name = "accountsdb-client"
connection_string = "http://mango.rpcpool.com:10001/"
retry_connection_sleep_secs = 30

[source.grpc_sources.tls]
ca_cert_path = "ca.pem"
client_cert_path = "client.pem"
client_key_path = "client.pem"
domain_name = "mango-accountsdb.rpcpool.com"

[source.snapshot]
rpc_http_url = "http://mango.rpcpool.com/35b811e91950fe4ccc82b8443117"
program_id = "mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68"

[[specs]]
market = "MNGO-PERP"
base_decimals = 6
quote_decimals = 6
base_lot_size = 1_000_000
quote_lot_size = 100
side = "bids"
public_key = "4XU8wH9ivp7x7ohhTbWUZabg5WVkF7sBtqQCmFEV6qiN"

[[specs]]
market = "MNGO-PERP"
base_decimals = 6
quote_decimals = 6
base_lot_size = 1_000_000
quote_lot_size = 100
side = "asks"
public_key = "4ZkS7ZZkxfsC3GtvvsHP3DFcUeByU9zzZELS4r8HCELo"

[[specs]]
market = "BTC-PERP"
base_decimals = 6
quote_decimals = 6
base_lot_size = 100
quote_lot_size = 10
side = "bids"
public_key = "Bc8XaK5UTuDSCBtiESSUxBSb9t6xczhbAJnesPamMRir"

[[specs]]
market = "BTC-PERP"
base_decimals = 6
quote_decimals = 6
base_lot_size = 100
quote_lot_size = 10
side = "asks"
public_key = "BkWRiarqxP5Gwx7115LQPbjRmr3NjuSRXWBnduXXLGWR"

[[specs]]
market = "ETH-PERP"
base_decimals = 6
quote_decimals = 6
base_lot_size = 1_000
quote_lot_size = 100
side = "bids"
public_key = "DQv2sWhaHYbKrobHH6jAdkAXw13mnDdM9hVfRQtrUcMe"

[[specs]]
market = "ETH-PERP"
base_decimals = 6
quote_decimals = 6
base_lot_size = 1_000
quote_lot_size = 100
side = "asks"
public_key = "8NhLMV6huneGAqijuUgUFSshbAfXxdNj6ZMHSLb9aW8K"

 [[specs]]
market = "SOL-PERP"
base_decimals = 9
quote_decimals = 6
base_lot_size = 10_000_000
quote_lot_size = 100
side = "bids"
public_key = "Fu8q5EiFunGwSRrjFKjRUoMABj5yCoMEPccMbUiAT6PD"

[[specs]]
market = "SOL-PERP"
base_decimals = 9
quote_decimals = 6
base_lot_size = 10_000_000
quote_lot_size = 100
side = "asks"
public_key = "9qUxMSWBGAeNmXusQHuLfgSuYJqADyYoNLwZ63JJSi6V"

[[specs]]
market = "SRM-PERP"
base_decimals = 6
quote_decimals = 6
base_lot_size = 100_000
quote_lot_size = 100
side = "bids"
public_key = "E8Dv9giJQgPqNaBxF9WKDUhJD7GZ5fwXfF1NQfeCCaQp"

[[specs]]
market = "SRM-PERP"
base_decimals = 6
quote_decimals = 6
base_lot_size = 100_000
quote_lot_size = 100
side = "asks"
public_key = "GMv773oHiNd4jaj8uQvr1kbzroY5BDK7QTNHD14ATjGJ"

[[specs]]
market = "RAY-PERP"
base_decimals = 6
quote_decimals = 6
base_lot_size = 100_000
quote_lot_size = 100
side = "bids"
public_key = "9AHm1nsxG1e3zkHnFLzYUXd17qnCgM7aFJDDApXXrhVU"

[[specs]]
market = "RAY-PERP"
base_decimals = 6
quote_decimals = 6
base_lot_size = 100_000
quote_lot_size = 100
side = "asks"
public_key = "43dVtcFTgDHHr32V6vhvxU2gg11wK7oyK8DdfTQ2pQsy"

[[specs]]
market = "FTT-PERP"
base_decimals = 6
quote_decimals = 6
base_lot_size = 100_000
quote_lot_size = 100
side = "bids"
public_key = "5xihpD8yz9vt95WSHVpW8pVykffW7h5VHb2LkhGBMUck"

[[specs]]
market = "FTT-PERP"
base_decimals = 6
quote_decimals = 6
base_lot_size = 100_000
quote_lot_size = 100
side = "asks"
public_key = "G9HtAEwHRYBrz9ZpdDJH8Qs1hEZqNJ1BPm3veBsmEXbX"

[[specs]]
market = "ADA-PERP"
base_decimals = 6
quote_decimals = 6
base_lot_size = 1_000_000
quote_lot_size = 100
side = "bids"
public_key = "ivYhvYgribqdCzDg4m8fUF9ejgJHE4mnRUseR4d9khN"

[[specs]]
market = "ADA-PERP"
base_decimals = 6
quote_decimals = 6
base_lot_size = 1_000_000
quote_lot_size = 100
side = "asks"
public_key = "F4UTmEXxEUgGSL7P3HePAuz3PsXvx6hWr256vqVnzxKE"

[[specs]]
market = "BNB-PERP"
base_decimals = 8
quote_decimals = 6
base_lot_size = 100_000
quote_lot_size = 100
side = "bids"
public_key = "6Pg82x4SSejLny5v1wSWs7QhnheLDq7EX1pMVY8LTsB3"

[[specs]]
market = "BNB-PERP"
base_decimals = 8
quote_decimals = 6
base_lot_size = 100_000
quote_lot_size = 100
side = "asks"
public_key = "6n2ooaNFP6X54ZiwDskhhVeW81F4hHNEibsJ8vfjVNDU"

[[specs]]
market = "AVAX-PERP"
base_decimals = 8
quote_decimals = 6
base_lot_size = 1_000_000
quote_lot_size = 100
side = "bids"
public_key = "BD1vpQjLXx7Rmd5n1SFNTLcwujPYTnFpoaArvPd9ixB9"

[[specs]]
market = "AVAX-PERP"
base_decimals = 8
quote_decimals = 6
base_lot_size = 1_000_000
quote_lot_size = 100
side = "asks"
public_key = "8Q11iGHXFTr267J4bgbeEeWPYPSANVcs6NQWHQK4UrNs"

[[specs]]
market = "GMT-PERP"
base_decimals = 9
quote_decimals = 6
base_lot_size = 1_000_000_000
quote_lot_size = 100
side = "bids"
public_key = "67jnTtxDdDqz6R18Do3AUUjBbZT3yysprGLhaucyKd93"

[[specs]]
market = "GMT-PERP"
base_decimals = 9
quote_decimals = 6
base_lot_size = 1_000_000_000
quote_lot_size = 100
side = "asks"
public_key = "DstVrGA3CBcq1r7op4yU7dX3sirzSgz1uicn63aYBMGz"
